version: "3.9"

services:
  flask_api:
    build: .
    container_name: flask_api
    ports:
      - "5000:5000"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: students_db
    depends_on:
      postgres_db:
        condition: service_healthy

  postgres_db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: students_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    # Exposé uniquement pour test local
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d students_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: